input { 

  jdbc {
    jdbc_driver_library => "/driver/mariadb-connector-j-8.4.0.jar"
    jdbc_driver_class => "com.mariadb.jdbc.Driver"
    jdbc_connection_string => "jdbc:mariadb://{{ .Values.redcap.config.database.auth.hostname }}:{{ default 3306 .Values.mariadb.primary.service.ports.mariadb }}/{{ .Values.redcap.config.database.auth.databaseName }}"
    jdbc_user => "{{ .Values.redcap.config.database.auth.username }}"
    jdbc_password => "{{ default .Values.redcap.config.database.auth.password `${MYSQL_PASSWD}` }}"
    schedule => "{{ .Values.audit.logsApi.config.pollingSchedule }}"
    last_run_metadata_path => "/bitnami/logstash/data/redcap-log-view-logstash_jdbc_last_run"
    use_column_value => true
    tracking_column_type => "numeric"
    tracking_column => "log_view_id"
    use_prepared_statements => true
    prepared_statement_name => "redcap-query-log-view"
    prepared_statement_bind_values => [":sql_last_value"]
    statement => "
      SELECT 
        *
      FROM
        redcap_log_view AS rlv
      WHERE
        rlv.log_view_id > ?
    "
  }
}

filter { 
  mutate { 
    add_field => { "source_table" => "redcap_log_view" } 
  } 
} 

output {

  http {
    id => "redcap-log-view"
    ssl_verification_mode => "full"
    cacert => "{{ .Values.audit.logsApi.config.caPath }}"
    headers => [ "X-OVH-TOKEN", "${AUDIT_TOKEN}" ]
    url => "https://{{ .Values.audit.logsApi.config.host }}:{{ .Values.audit.logsApi.config.port }}"
    http_method => "post"
    retry_non_idempotent => true
    format => json_batch
    http_compression => true
  }
}